"""Read-only instance health, resource usage, logs, and dashboard queries."""

import logging
import os
import sqlite3
import stat
import tempfile
import threading
import time
from datetime import datetime, timezone
from . import config
from . import container_runtime
from .db import (
    get_instance,
    get_account_by_id,
)
from .instance_environment import (
    connect_tenant_db,
    open_tenant_file,
    read_tenant_file,
)
from .instance_paths import (
    _instance_bind_host,
    _instance_dir_for,
    _instance_url,
    _pid_file,
    _tts_worker_pid_file,
)

logger = logging.getLogger(__name__)


_HEALTH_CACHE_TTL = 10.0


_NEGATIVE_HEALTH_CACHE_TTL = 3.0


_STORAGE_CACHE_TTL = 5.0


_health_cache = {}


_storage_cache = {}


_cache_lock = threading.Lock()


_INSTANCE_OP_SEMAPHORE = threading.BoundedSemaphore(16)


_HEALTH_CHECK_HTTP_TIMEOUT = 2.0

_LOG_TAIL_BYTES = 256 * 1024  # 256 KiB
_READABLE_INSTANCE_LOGS = ("error.log", "access.log")


def _read_pid(data_dir):
    """Return the numeric PID stored in the PID file, or ``None``."""
    return _read_pid_path(_pid_file(data_dir))


def _read_tts_worker_pid(data_dir):
    """Return the numeric TTS worker PID for *data_dir*, or ``None``."""
    return _read_pid_path(_tts_worker_pid_file(data_dir))


def _read_pid_path(path):
    """Return the numeric PID stored at *path*, or ``None``.

    The file sits in the tenant's data directory, so it is read without
    following links and a FIFO planted there cannot block the portal.
    """
    try:
        return int(read_tenant_file(os.path.dirname(path), path, max_bytes=64).strip())
    except (OSError, ValueError):
        return None


def _is_process_alive(pid):
    """Check whether *any* process with the given *pid* is running.

    NOTE: This is a low-level liveness probe.  It cannot tell us whether
    *pid* is the Gunicorn we spawned or some unrelated process whose PID
    happens to be reused after a VPS reboot.  Callers that need to know
    "is OUR instance running?" must use :func:`_is_our_instance_process`
    instead, otherwise stale PID files written before a reboot keep
    instances stuck in a permanent unhealthy state because the kernel
    reuses low PIDs (systemd, kthreadd, dbus, …) and ``kill -0`` succeeds
    against those unrelated processes.
    """
    if pid is None:
        return False
    try:
        os.kill(pid, 0)
        return True
    except (ProcessLookupError, PermissionError):
        return False


def _current_boot_id():
    """Return the kernel boot id, or ``None`` if it cannot be read.

    The boot id is a UUID generated by the kernel each time the machine
    boots and is stable for the entire lifetime of that boot.  We use it
    to detect PID files written before a reboot: after the system comes
    back up the boot id changes, so a stored boot id that does not match
    the current one means the recorded PID belongs to a previous boot
    and may now be reused by an unrelated process.
    """
    try:
        with open("/proc/sys/kernel/random/boot_id", "r", encoding="utf-8") as f:
            return f.read().strip() or None
    except OSError:
        return None


def _boot_id_path(data_dir):
    return os.path.join(data_dir, ".boot_id")


def _read_stored_boot_id(data_dir):
    """Return the boot id stored alongside the PID file, or ``None``."""
    try:
        raw = read_tenant_file(data_dir, _boot_id_path(data_dir), max_bytes=64)
    except (OSError, ValueError):
        return None
    return raw.decode("utf-8", errors="replace").strip() or None


def _write_boot_id(data_dir):
    """Persist the current kernel boot id next to the PID file.

    Called immediately after Gunicorn writes its PID so we can later tell
    whether that PID belongs to this boot.  No-op (and best-effort safe)
    on platforms where ``/proc/sys/kernel/random/boot_id`` is missing.
    """
    boot_id = _current_boot_id()
    if not boot_id:
        return
    path = _boot_id_path(data_dir)
    try:
        os.makedirs(data_dir, exist_ok=True)
        fd, tmp_path = tempfile.mkstemp(dir=data_dir, prefix=".boot_id_")
        try:
            os.write(fd, boot_id.encode("utf-8"))
            os.close(fd)
            os.replace(tmp_path, path)
        except BaseException:
            try:
                os.close(fd)
            except OSError:
                pass
            try:
                os.unlink(tmp_path)
            except OSError:
                pass
            raise
    except OSError:
        # Best effort: the worst case is that we fall back to the
        # cmdline-only check on the next liveness probe.
        logger.debug("Failed to persist boot id under %s", data_dir, exc_info=True)


def _read_proc_cmdline(pid):
    """Return ``/proc/{pid}/cmdline`` as a string, or ``None``."""
    if pid is None:
        return None
    try:
        with open(f"/proc/{pid}/cmdline", "rb") as f:
            return f.read().decode("utf-8", "replace")
    except (FileNotFoundError, PermissionError, OSError):
        return None


def _read_proc_environ(pid):
    """Return ``/proc/{pid}/environ`` as a dict, or ``None`` when unavailable."""
    if pid is None:
        return None
    try:
        with open(f"/proc/{pid}/environ", "rb") as f:
            raw = f.read()
    except (FileNotFoundError, PermissionError, OSError):
        return None
    env = {}
    for part in raw.split(b"\0"):
        if not part or b"=" not in part:
            continue
        key, value = part.split(b"=", 1)
        env[key.decode("utf-8", "replace")] = value.decode("utf-8", "replace")
    return env


def _is_our_instance_process(pid, data_dir, port=None):
    """Return ``True`` only if *pid* is OUR Gunicorn for this instance.

    This is the check that ``_start_process``, ``recover_running_instances``,
    ``check_instance_health`` and the lazy-recovery path use to decide
    whether the recorded PID is still serving the instance.  It guards
    against three failure modes that ``_is_process_alive`` alone cannot
    detect:

    1. **PID reuse after a VPS reboot.**  The kernel resets the PID
       allocator on boot; the PID written before the reboot may now
       belong to systemd, kthreadd, dbus, sshd, etc.  We persist the
       kernel boot id alongside the PID file and reject any stored boot
       id that does not match the current one.

    2. **PID reuse during the same boot.**  When a Gunicorn master dies
       and the kernel later wraps PIDs back around, an unrelated process
       may end up with the same numeric PID.  We verify ``/proc/{pid}/
       cmdline`` contains ``gunicorn`` so we never claim some random
       process is our wiki worker.

    3. **Cross-instance PID reuse.**  When *port* is provided we also
       require the cmdline to mention that bind port, so a leftover
       Gunicorn from a different instance is not mistaken for ours.

    On platforms without ``/proc`` (the production stack is Linux only,
    but tests run cross-platform) we fall back to the basic alive check
    so we do not break developer machines.
    """
    if config.HOSTING_INSTANCE_RUNTIME == "docker":
        return container_runtime.container_is_running(data_dir)

    if not _is_process_alive(pid):
        return False

    # Boot id must match the current boot, if we have one stored.
    stored_boot_id = _read_stored_boot_id(data_dir)
    current_boot_id = _current_boot_id()
    if stored_boot_id and current_boot_id and stored_boot_id != current_boot_id:
        return False

    cmdline = _read_proc_cmdline(pid)
    if cmdline is None:
        # No /proc available: boot id alone is the best we can do.  If
        # we got this far it either matched or was unavailable on both
        # ends, so treat the PID as ours.
        return True

    if "gunicorn" not in cmdline:
        return False

    if port is not None and f":{port}" not in cmdline:
        return False

    return True


def _is_our_tts_worker_process(pid, data_dir):
    """Return True only if *pid* is the TTS worker for this instance."""
    if not _is_process_alive(pid):
        return False

    cmdline = _read_proc_cmdline(pid)
    environ = _read_proc_environ(pid)
    if cmdline is None and environ is None:
        # Developer platforms without /proc: alive is the best available signal.
        return True
    if cmdline is not None and "tts_worker.py" not in cmdline:
        return False
    if environ is not None:
        expected = os.path.realpath(data_dir)
        actual = environ.get("BW_INSTANCE_DIR")
        if actual and os.path.realpath(actual) != expected:
            return False
    return True


def _is_port_accepting(host, port, timeout=1.0):
    """Return ``True`` if *port* is accepting TCP connections on *host*."""
    import socket

    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(timeout)
            s.connect((host, port))
        return True
    except (OSError, ConnectionRefusedError):
        return False


def _instance_accepts_connections(inst):
    """Return ``True`` if *inst* is currently accepting TCP connections."""
    port = int(inst["port"])
    bind_host = _instance_bind_host()
    connect_host = "127.0.0.1" if bind_host == "0.0.0.0" else bind_host
    return _is_port_accepting(connect_host, port, timeout=1.0)


def _instance_http_ready(inst, timeout=None):
    """Return ``True`` if the instance answers its liveness endpoint.

    *timeout* defaults to :data:`_HEALTH_CHECK_HTTP_TIMEOUT` (a short
    per-instance timeout) so that a stuck or slow instance cannot stall
    health checks for other instances.

    In Docker mode the health check connects directly to the container's
    bridge IP rather than going through the published host port.  Docker's
    ``--internal`` network flag prevents the iptables DNAT/ACCEPT rules
    needed for ``--publish`` to work on some Docker/kernel combinations, so
    port publishing is unreliable for health checks.  The host can always
    reach a container on its own bridge network directly, regardless of the
    ``--internal`` flag, so this path is always reliable.
    """
    import http.client

    if timeout is None:
        timeout = _HEALTH_CHECK_HTTP_TIMEOUT

    if config.HOSTING_INSTANCE_RUNTIME == "docker":
        data_dir = _instance_dir_for(inst)
        connect_host = container_runtime.container_ip(data_dir)
        if not connect_host:
            return False
        port = config.HOSTING_CONTAINER_INTERNAL_PORT
    else:
        port = int(inst["port"])
        bind_host = _instance_bind_host()
        connect_host = "127.0.0.1" if bind_host == "0.0.0.0" else bind_host
        if connect_host == "::":
            connect_host = "::1"

    conn = None
    try:
        conn = http.client.HTTPConnection(connect_host, port, timeout=timeout)
        conn.request("GET", "/healthz")
        resp = conn.getresponse()
        resp.read(1024)
        return 200 <= resp.status < 500
    except (OSError, http.client.HTTPException):
        return False
    finally:
        try:
            conn.close()
        except Exception:
            pass


def _invalidate_instance_caches(subdomain):
    """Clear cached health/storage data for *subdomain*."""
    with _cache_lock:
        _health_cache.pop(subdomain, None)
        _storage_cache.pop(subdomain, None)
    # Also clear the Docker container-IP cache in the subdomain proxy so that
    # a stop/restart immediately picks up the new bridge IP rather than
    # waiting for the TTL to expire and proxying to the old (dead) container.
    try:
        from . import _subdomain_proxy as _proxy_mod

        with _proxy_mod._container_ip_cache_lock:
            keys_to_drop = [
                k for k in _proxy_mod._container_ip_cache if k[0] == subdomain
            ]
            for k in keys_to_drop:
                _proxy_mod._container_ip_cache.pop(k, None)
    except Exception:
        pass


def _get_cached_health(subdomain):
    with _cache_lock:
        entry = _health_cache.get(subdomain)
        if not entry:
            return None
        checked_at, value = entry
        ttl = _HEALTH_CACHE_TTL if value else _NEGATIVE_HEALTH_CACHE_TTL
        if time.monotonic() - checked_at > ttl:
            _health_cache.pop(subdomain, None)
            return None
        return value


def _set_cached_health(subdomain, value):
    with _cache_lock:
        _health_cache[subdomain] = (time.monotonic(), value)


def _get_cached_storage(data_dir):
    with _cache_lock:
        entry = _storage_cache.get(data_dir)
        if not entry:
            return None
        checked_at, value = entry
        if time.monotonic() - checked_at > _STORAGE_CACHE_TTL:
            _storage_cache.pop(data_dir, None)
            return None
        return value


def _set_cached_storage(data_dir, value):
    with _cache_lock:
        _storage_cache[data_dir] = (time.monotonic(), value)


def get_storage_bytes(data_dir, walk_timeout=10.0, *, force_refresh=False):
    """Return the total size (in bytes) of all files under *data_dir*.

    Uses the global concurrency semaphore so a slow filesystem on one
    instance cannot block storage queries for other instances.

    *walk_timeout* bounds the amount of wall time spent walking the
    directory tree: if the filesystem stalls (NFS hang, FUSE deadlock,
    etc.), we return the bytes counted so far rather than blocking the
    semaphore indefinitely.
    """
    if not force_refresh:
        cached = _get_cached_storage(data_dir)
        if cached is not None:
            return cached

    acquired = _INSTANCE_OP_SEMAPHORE.acquire(blocking=True, timeout=5.0)
    if not acquired:
        logger.warning(
            "get_storage_bytes timed out waiting for op semaphore on %s", data_dir
        )
        return 0
    try:
        total = 0
        walk_deadline = time.monotonic() + walk_timeout
        try:
            for dirpath, _dirnames, filenames in os.walk(data_dir):
                if time.monotonic() > walk_deadline:
                    logger.warning(
                        "get_storage_bytes walk timeout (%s) on %s: "
                        "returning partial count %d",
                        walk_timeout,
                        data_dir,
                        total,
                    )
                    break
                for fn in filenames:
                    fp = os.path.join(dirpath, fn)
                    # lstat, so a link to a file outside the tenant is not
                    # counted and cannot be used to probe host file sizes.
                    try:
                        st = os.lstat(fp)
                    except OSError:
                        continue
                    if stat.S_ISREG(st.st_mode):
                        total += st.st_size
        except OSError:
            pass
    finally:
        _INSTANCE_OP_SEMAPHORE.release()
    _set_cached_storage(data_dir, total)
    return total


def _instance_storage_limit_mb(inst):
    """Return the effective storage cap for *inst* in MB, or ``None`` for unlimited."""
    # ``account_is_admin`` is attached by callers that have owner account
    # context (dashboard/detail/admin views).  When absent we safely fall
    # back to row-local fields only.
    if not isinstance(inst, dict):
        inst = dict(inst)
    if bool(inst.get("account_is_admin")):
        return None
    if str(inst.get("domain_mode") or "hosting") == "apex":
        return None
    value = inst.get("storage_limit_mb")
    if value is None:
        return int(config.INSTANCE_STORAGE_LIMIT_MB)
    try:
        parsed = int(value)
    except (TypeError, ValueError):
        return int(config.INSTANCE_STORAGE_LIMIT_MB)
    if parsed <= 0:
        return None
    return parsed


_PROCESS_ALIVE_SOCKET_TIMEOUT = 0.15


def check_instance_process_alive(inst):
    """Lightweight check: is our Gunicorn master *and its listening socket* alive for *inst*?

    Returns ``True`` when:

    1. The PID file points at a live Gunicorn process that belongs to
       this instance, and
    2. The bound TCP port is accepting connections.

    The TCP probe is intentionally tiny (``_PROCESS_ALIVE_SOCKET_TIMEOUT``
    seconds, default 0.15 s). It's a local-loopback ``connect_ex`` so on
    Linux the kernel returns immediately when the listener is alive and
    just-as-immediately when it isn't.  The cost on the hot proxy path
    is well under a millisecond when the instance is healthy.

    Does NOT make an HTTP request: that's intentionally left to the full
    ``check_instance_health`` path, which the lazy-recovery worker still
    uses to decide whether to escalate to a force-restart.  This split
    means a wedged Gunicorn master (PID alive, workers stuck) no longer
    passes the lightweight check and silently serves slow requests. The
    proxy will short-circuit it to the "Starting up…" splash and trigger
    lazy recovery immediately.
    """
    if inst["status"] != "running":
        return False
    if not isinstance(inst, dict):
        inst = dict(inst)
    data_dir = _instance_dir_for(inst)
    pid = _read_pid(data_dir)
    port = int(inst["port"]) if inst.get("port") is not None else None
    if not _is_our_instance_process(pid, data_dir, port=port):
        return False
    # In Docker mode ``_is_our_instance_process`` delegates entirely to
    # ``container_is_running`` (docker inspect), which already confirms the
    # container is alive.  Probing the published host port is unreliable
    # because Docker's ``--internal`` network flag suppresses the iptables
    # DNAT/ACCEPT rules that port publishing requires, so the probe would
    # always return False even when the container is healthy.
    if config.HOSTING_INSTANCE_RUNTIME == "docker":
        return True
    if port is None:
        return True
    bind_host = _instance_bind_host()
    connect_host = "127.0.0.1" if bind_host == "0.0.0.0" else bind_host
    if connect_host == "::":
        connect_host = "::1"
    return _is_port_accepting(connect_host, port, timeout=_PROCESS_ALIVE_SOCKET_TIMEOUT)


def check_instance_health(inst):
    """Check whether the process for *inst* is alive.

    Returns ``True`` if the instance status is ``'running'`` and its
    process is actually alive and reachable on its bound TCP port.

    Uses the global concurrency semaphore so a slow / stuck health check
    on one instance cannot block health checks for other instances.
    """
    if inst["status"] != "running":
        return False
    cached = _get_cached_health(inst["subdomain"])
    if cached is not None:
        return cached
    if not isinstance(inst, dict):
        inst = dict(inst)
    data_dir = _instance_dir_for(inst)
    pid = _read_pid(data_dir)
    port = int(inst["port"]) if inst.get("port") is not None else None
    acquired = _INSTANCE_OP_SEMAPHORE.acquire(blocking=True, timeout=10.0)
    if not acquired:
        logger.warning(
            "Health check for instance %s timed out waiting for op semaphore",
            inst["id"],
        )
        return False
    try:
        healthy = _is_our_instance_process(
            pid, data_dir, port=port
        ) and _instance_http_ready(inst)
    except Exception:
        logger.exception("Health check failed for instance %s", inst["id"])
        healthy = False
    finally:
        _INSTANCE_OP_SEMAPHORE.release()
    _set_cached_health(inst["subdomain"], healthy)
    return healthy


def _enrich_instance_for_dashboard(inst, now):
    """Add URL, countdown, health, and storage fields to *inst* dict in-place."""
    inst["url"] = _instance_url(inst)

    # Compute expiry/remaining for non-terminated instances.
    # For terminated instances in grace period, show grace period info.
    if inst["status"] == "terminated":
        inst["days_remaining"] = 0
        inst["hours_remaining"] = 0
        inst["display_hours"] = 0
        inst["is_expired"] = True

        # Grace period info
        inst["grace_period_active"] = False
        inst["grace_period_ends_at"] = None
        inst["grace_days_remaining"] = 0
        retained_until = inst.get("data_retained_until")
        if retained_until:
            try:
                ends_at = datetime.fromisoformat(retained_until)
                grace_remaining = ends_at - now
                if grace_remaining.total_seconds() > 0:
                    inst["grace_period_active"] = True
                    inst["grace_period_ends_at"] = retained_until
                    inst["grace_days_remaining"] = max(0, grace_remaining.days)
            except (ValueError, TypeError):
                pass
        inst["grace_period_suspended"] = bool(inst.get("grace_period_suspended"))
    else:
        inst["grace_period_active"] = False
        inst["grace_period_ends_at"] = None
        inst["grace_days_remaining"] = 0
        inst["grace_period_suspended"] = False
        try:
            expires = datetime.fromisoformat(inst["expires_at"])
            remaining = expires - now
            inst["days_remaining"] = max(0, remaining.days)
            total_hours = max(0, int(remaining.total_seconds() // 3600))
            inst["hours_remaining"] = total_hours
            inst["display_hours"] = total_hours % 24
            inst["is_expired"] = remaining.total_seconds() <= 0
        except (ValueError, TypeError):
            inst["days_remaining"] = 0
            inst["hours_remaining"] = 0
            inst["display_hours"] = 0
            inst["is_expired"] = True

    try:
        data_dir = _instance_dir_for(inst)
        if inst["status"] == "running":
            inst["is_healthy"] = check_instance_health(inst)
        else:
            inst["is_healthy"] = False
        storage_bytes = get_storage_bytes(data_dir)
        limit_mb = _instance_storage_limit_mb(inst)
        inst["storage_mb"] = round(storage_bytes / (1024 * 1024), 1)
        inst["storage_limit_mb"] = limit_mb
        if limit_mb is None:
            inst["storage_pct"] = 0
        else:
            inst["storage_pct"] = min(
                100,
                round(storage_bytes / (limit_mb * 1024 * 1024) * 100, 1),
            )
    except Exception:
        logger.warning(
            "Failed to enrich dashboard data for instance %s",
            inst["id"],
            exc_info=True,
        )
        inst["is_healthy"] = False
        inst["storage_mb"] = 0
        inst["storage_limit_mb"] = None
        inst["storage_pct"] = 0


def get_dashboard_instances(account_id):
    """Return instance data enriched with URL, countdown, health, and storage info.

    Shows running, stopped, suspended, AND terminated instances that are
    still within their grace period so users can see expired instances and
    download their data.  Also includes instances where the account is a
    collaborator (shared instances), tagged with ``is_shared=True`` and
    ``owner_username``.
    """
    from .db import get_hosting_db_context, get_shared_instances_for_account

    account = get_account_by_id(account_id)
    owner_is_admin = bool(account and account["is_admin"])
    now = datetime.now(timezone.utc)

    # Recovery retention is an operator safety mechanism.  Regular owners see
    # a terminated wiki disappear immediately; platform admins retain the
    # recovery/export view during the configured grace window.
    # When allow_owner_download_expired is enabled, non-admin owners also see
    # their terminated wikis during the grace period.
    from .db import get_allow_owner_download_expired

    owner_can_download_expired = owner_is_admin or get_allow_owner_download_expired()
    with get_hosting_db_context() as conn:
        if owner_can_download_expired:
            rows = conn.execute(
                "SELECT * FROM instances WHERE account_id=? AND "
                "(status != 'terminated' OR "
                "(status='terminated' AND data_retained_until IS NOT NULL AND data_retained_until > ?)) "
                "ORDER BY created_at DESC",
                (account_id, now.isoformat()),
            ).fetchall()
        else:
            rows = conn.execute(
                "SELECT * FROM instances WHERE account_id=? AND status != 'terminated' ORDER BY created_at DESC",
                (account_id,),
            ).fetchall()

    results = []
    for row in rows:
        inst = dict(row)
        inst["account_is_admin"] = owner_is_admin
        inst["is_shared"] = False
        inst["owner_username"] = None
        _enrich_instance_for_dashboard(inst, now)
        results.append(inst)

    # Append shared instances (where account is a collaborator, not owner)
    shared_rows = get_shared_instances_for_account(account_id)
    for row in shared_rows:
        inst = dict(row)
        inst["account_is_admin"] = owner_is_admin
        inst["is_shared"] = True
        inst["owner_username"] = row.get("owner_username", "unknown")
        _enrich_instance_for_dashboard(inst, now)
        results.append(inst)

    return results


def get_admin_instances():
    """Return all instances (for admin dashboard) with enriched data."""
    from .db import get_all_instances

    rows = get_all_instances()
    results = []
    now = datetime.now(timezone.utc)
    for row in rows:
        inst = dict(row)
        inst["url"] = _instance_url(inst)
        inst["account_is_admin"] = bool(inst.get("account_is_admin"))
        try:
            expires = datetime.fromisoformat(inst["expires_at"])
            remaining = expires - now
            inst["days_remaining"] = max(0, remaining.days)
            inst["display_hours"] = max(0, int(remaining.total_seconds() // 3600)) % 24
            inst["is_expired"] = remaining.total_seconds() <= 0
        except (ValueError, TypeError):
            inst["days_remaining"] = 0
            inst["display_hours"] = 0
            inst["is_expired"] = True

        # Grace-period bookkeeping for terminated instances.  ``data_retained_until``
        # is set when the instance is moved into the grace window and cleared when
        # the data dir is hard-deleted by the periodic cleanup (or the instance is
        # restored).  ``grace_period_active`` is True while the on-disk data is
        # still recoverable.
        inst["grace_period_active"] = False
        inst["grace_period_ends_at"] = None
        inst["grace_days_remaining"] = 0
        retained_until = inst.get("data_retained_until")
        if inst["status"] == "terminated" and retained_until:
            try:
                ends_at = datetime.fromisoformat(retained_until)
                grace_remaining = ends_at - now
                if grace_remaining.total_seconds() > 0:
                    inst["grace_period_active"] = True
                    inst["grace_period_ends_at"] = retained_until
                    inst["grace_days_remaining"] = max(0, grace_remaining.days)
            except (ValueError, TypeError):
                pass

        try:
            data_dir = _instance_dir_for(inst)
            inst["is_healthy"] = check_instance_health(inst)
            storage_bytes = get_storage_bytes(data_dir)
            limit_mb = _instance_storage_limit_mb(inst)
            inst["storage_mb"] = round(storage_bytes / (1024 * 1024), 1)
            inst["storage_limit_mb"] = limit_mb
            if limit_mb is None:
                inst["storage_pct"] = 0
            else:
                inst["storage_pct"] = min(
                    100,
                    round(storage_bytes / (limit_mb * 1024 * 1024) * 100, 1),
                )
        except Exception:
            logger.warning(
                "Failed to enrich admin dashboard data for instance %s",
                inst["id"],
                exc_info=True,
            )
            inst["is_healthy"] = False
            inst["storage_mb"] = 0
            inst["storage_limit_mb"] = None
            inst["storage_pct"] = 0
        results.append(inst)
    return results


def get_instance_detail(instance_id):
    """Return enriched detail data for a single instance.

    Returns ``None`` if the instance does not exist.  The returned dict
    extends the raw DB row with URL, countdown, health, and storage fields.
    For terminated instances in grace period, includes grace period and
    suspension status.
    """
    inst = get_instance(instance_id)
    if inst is None:
        return None
    inst = dict(inst)
    owner = get_account_by_id(inst["account_id"])
    inst["account_is_admin"] = bool(owner and owner["is_admin"])
    if owner is not None:
        inst["account_username"] = owner["username"]
    inst["url"] = _instance_url(inst)
    now = datetime.now(timezone.utc)

    # Grace period info for terminated instances
    inst["grace_period_active"] = False
    inst["grace_period_ends_at"] = None
    inst["grace_days_remaining"] = 0
    inst["grace_period_suspended"] = bool(inst.get("grace_period_suspended"))

    if inst["status"] == "terminated":
        inst["days_remaining"] = 0
        inst["hours_remaining"] = 0
        inst["display_hours"] = 0
        inst["is_expired"] = True
        retained_until = inst.get("data_retained_until")
        if retained_until:
            try:
                ends_at = datetime.fromisoformat(retained_until)
                grace_remaining = ends_at - now
                if grace_remaining.total_seconds() > 0:
                    inst["grace_period_active"] = True
                    inst["grace_period_ends_at"] = retained_until
                    inst["grace_days_remaining"] = max(0, grace_remaining.days)
            except (ValueError, TypeError):
                pass
    else:
        try:
            expires = datetime.fromisoformat(inst["expires_at"])
            remaining = expires - now
            inst["days_remaining"] = max(0, remaining.days)
            total_hours = max(0, int(remaining.total_seconds() // 3600))
            inst["hours_remaining"] = total_hours
            inst["display_hours"] = total_hours % 24
            inst["is_expired"] = remaining.total_seconds() <= 0
        except (ValueError, TypeError):
            inst["days_remaining"] = 0
            inst["hours_remaining"] = 0
            inst["display_hours"] = 0
            inst["is_expired"] = True

    data_dir = _instance_dir_for(inst)
    inst["is_healthy"] = (
        check_instance_health(inst) if inst["status"] == "running" else False
    )
    storage_bytes = get_storage_bytes(data_dir)
    limit_mb = _instance_storage_limit_mb(inst)
    inst["storage_mb"] = round(storage_bytes / (1024 * 1024), 1)
    inst["storage_limit_mb"] = limit_mb
    if limit_mb is None:
        inst["storage_pct"] = 0
    else:
        inst["storage_pct"] = min(
            100,
            round(storage_bytes / (limit_mb * 1024 * 1024) * 100, 1),
        )
    return inst


def read_instance_log(instance_id, log_name="error.log", *, max_bytes=_LOG_TAIL_BYTES):
    """Return the tail of an instance log for the admin debug viewer.

    Returns ``(content, path, size_bytes, error)`` where:

    * ``content``: the last ``max_bytes`` of the log decoded as UTF-8
      (errors replaced) or ``""`` when the log does not exist yet.
    * ``path``: absolute filesystem path to the log (useful for the UI to
      tell admins where to ``tail -f`` if they want a live stream).
    * ``size_bytes``: full on-disk size of the log; lets the UI tell the
      admin they are looking at a truncated tail.
    * ``error``: ``None`` on success or a human-readable failure reason.

    Only ``error.log`` and ``access.log`` are accepted as ``log_name`` to
    guard against path-traversal attempts through the query string.
    """
    if log_name not in _READABLE_INSTANCE_LOGS:
        return "", None, 0, "Unsupported log name."

    inst = get_instance(instance_id)
    if inst is None:
        return "", None, 0, "Instance not found."

    try:
        data_dir = _instance_dir_for(inst)
    except ValueError:
        return "", None, 0, "Instance directory is not accessible."
    log_path = os.path.join(data_dir, log_name)

    # The tenant can replace its log with a link to a portal file, so open
    # it without following links and take the size from what was opened.
    try:
        fd = open_tenant_file(data_dir, log_path)
    except FileNotFoundError:
        return "", log_path, 0, None
    except (OSError, ValueError):
        logger.warning("Not reading log %s for instance %s: not a regular file", log_path, instance_id)
        return "", log_path, 0, "The log is not a regular file inside the instance directory."
    try:
        with os.fdopen(fd, "rb") as fh:
            size = os.fstat(fh.fileno()).st_size
            tail_bytes = max(0, int(max_bytes))
            if size > tail_bytes:
                fh.seek(-tail_bytes, os.SEEK_END)
            data = fh.read(tail_bytes)
        return data.decode("utf-8", errors="replace"), log_path, size, None
    except OSError:
        logger.exception("Failed to read log %s for instance %s", log_path, instance_id)
        return "", log_path, 0, "Failed to read the log file."


def read_instance_analytics(instance_id, *, days=30):
    """Return a daily analytics roll-up for *instance_id*.

    Opens the instance's ``bananawiki.db`` read-only and queries the
    ``analytics_daily`` table via :func:`db.get_analytics_summary`.
    Works for any non-terminated instance: the portal never writes to
    the wiki's database so concurrent reads are safe even while the
    instance is running.

    Returns ``(summary, error)`` where:

    * ``summary`` is the dict produced by ``get_analytics_summary``
      (``{"totals": {...}, "daily": [...], "window_days": N}``) or
      ``None`` when *error* is set.
    * ``error`` is ``None`` on success or a short human-readable
      message (e.g. ``"Instance not found."``) suitable for ``flash()``.

    Importing the wiki's ``db`` package lazily keeps the hosting portal
    free of its module-level side effects until analytics are actually
    requested.
    """
    inst = get_instance(instance_id)
    if inst is None:
        return None, "Instance not found."

    data_dir = _instance_dir_for(inst)
    db_path = os.path.join(data_dir, "bananawiki.db")
    if not os.path.lexists(db_path):
        # Terminated instances inside their grace window keep the DB on
        # disk; once the cleanup wipes it there's nothing to read.
        return None, "No analytics data is available for this instance."

    # Lazy import: the wiki ``db`` package pulls in plenty of helpers
    # we don't otherwise need in the portal process.
    from db import get_analytics_summary  # type: ignore

    # Open the wiki DB read-only, so the portal never writes to a running
    # instance, and through connect_tenant_db, so a tenant that links its
    # database to another wiki's cannot read that wiki's analytics.
    try:
        ro = connect_tenant_db(data_dir, db_path, read_only=True, timeout=10, max_seconds=10)
    except (OSError, ValueError):
        logger.warning("Not reading analytics for instance %s: unsafe database path", instance_id)
        return None, "No analytics data is available for this instance."
    except sqlite3.Error:
        logger.exception("Failed to read analytics for instance %s", instance_id)
        return None, "Failed to read analytics for this instance."
    try:
        ro.row_factory = sqlite3.Row
        summary = get_analytics_summary(days=days, conn=ro)
    except sqlite3.Error:
        logger.exception("Failed to read analytics for instance %s", instance_id)
        return None, "Failed to read analytics for this instance."
    finally:
        ro.close()

    return summary, None


def get_platform_stats():
    """Return a summary dict of platform-wide statistics for the admin dashboard."""
    from .db import get_all_accounts, get_all_instances

    accounts = get_all_accounts()
    instances_raw = get_all_instances()

    total_accounts = len(accounts)
    total_instances = len(instances_raw)
    running = sum(1 for i in instances_raw if i["status"] == "running")
    stopped = sum(1 for i in instances_raw if i["status"] == "stopped")
    terminated = sum(1 for i in instances_raw if i["status"] == "terminated")

    total_storage_mb = 0.0
    for inst in instances_raw:
        if inst["status"] != "terminated":
            try:
                data_dir = _instance_dir_for(inst)
                total_storage_mb += get_storage_bytes(data_dir) / (1024 * 1024)
            except Exception:
                pass

    healthy = 0
    for inst in instances_raw:
        if inst["status"] == "running":
            if check_instance_health(dict(inst)):
                healthy += 1

    return {
        "total_accounts": total_accounts,
        "total_instances": total_instances,
        "running": running,
        "stopped": stopped,
        "terminated": terminated,
        "healthy": healthy,
        "total_storage_mb": round(total_storage_mb, 1),
        "storage_limit_mb": config.INSTANCE_STORAGE_LIMIT_MB,
    }
