"""Database helpers for the hosting platform."""

from ._connection import (  # noqa: F401
    get_hosting_db,
    get_hosting_db_context,
    create_consistent_db_copy,
)
from ._schema import init_hosting_db  # noqa: F401
from ._accounts import (  # noqa: F401
    create_account,
    create_account_atomic_first_admin,
    create_signup_account,
    get_account_by_id,
    get_account_by_username,
    get_account_by_email,
    issue_email_verification,
    clear_email_verification,
    verify_email_token,
    issue_password_reset,
    consume_password_reset,
    get_all_accounts,
    set_account_admin,
    count_admin_accounts,
    count_active_admin_accounts,
    change_account_password,
    delete_account,
    purge_deleted_account_tombstones,
    log_hosting_impersonation_start,
    log_hosting_impersonation_stop,
    suspend_account,
    unsuspend_account,
    is_account_suspended,
    check_account_suspension_expired,
    cleanup_expired_account_suspensions,
    record_account_suspension_action,
    get_account_suspension_history,
    get_pending_accounts,
    count_pending_hosting_accounts,
    approve_hosting_account,
    deny_hosting_account,
    cleanup_denied_hosting_accounts,
    count_denied_hosting_accounts,
    approve_all_pending_hosting_accounts,
    set_account_theme_mode,
    get_account_theme_mode,
    update_hosting_account,
    flag_email_invalid,
    clear_email_flag,
    set_pending_deletion,
    cancel_pending_deletion,
    get_pending_deletion_accounts,
)
from ._instances import (  # noqa: F401
    create_instance,
    clear_instance_password,
    get_instance,
    get_instance_by_subdomain,
    get_apex_instance_by_subdomain,
    find_available_instance_subdomain,
    update_instance_identity,
    get_instances_for_account,
    count_active_instances,
    update_instance_status,
    terminate_instance,
    set_instance_upload_policy,
    archive_terminated_subdomain,
    terminate_and_archive_instance,
    clear_instance_data_retention,
    get_instances_with_expired_grace_period,
    restore_instance_in_place,
    get_all_active_instances,
    get_all_instances,
    get_expired_instances,
    delete_instance,
    transfer_instance_ownership,
    is_instance_suspension_active,
    check_instance_suspension_expired,
    get_expired_instance_suspensions,
    record_instance_suspension_action,
    get_instance_suspension_history,
    suspend_grace_period_instance,
    unsuspend_grace_period_instance,
    is_grace_period_suspended,
)
from ._rate_limiting import (  # noqa: F401
    record_hosting_login_attempt,
    count_recent_hosting_login_attempts,
    clear_hosting_login_attempts,
    check_and_record_hosting_rate_limit,
    get_hosting_rate_limit_retry_after,
)
from ._sessions import (  # noqa: F401
    create_hosting_session,
    get_hosting_session,
    get_hosting_session_id,
    list_active_hosting_sessions,
    list_hosting_session_history,
    clear_hosting_session_history,
    touch_hosting_session,
    revoke_hosting_session,
    revoke_hosting_session_token,
    revoke_other_hosting_sessions,
    revoke_all_hosting_sessions,
    update_hosting_session_version,
    change_hosting_password_preserving_session,
)
from ._settings import (  # noqa: F401
    get_hosting_settings,
    update_hosting_settings,
    get_grace_period_days,
    DEFAULT_GRACE_PERIOD_DAYS,
    get_signup_mode,
    get_hosting_activation_required,
    get_hosting_activation_denied_timeout_seconds,
    get_hosting_activation_denied_deletion_enabled,
    get_allow_owner_delete_expired,
    get_allow_owner_download_expired,
    get_hosting_api_enabled,
    get_approval_notify_email,
    get_approval_notify_mode,
    get_approval_notify_digest_hours,
    get_approval_notify_last_digest_at,
    DEFAULT_APPROVAL_NOTIFY_DIGEST_HOURS,
)
from ._invite_codes import (  # noqa: F401
    create_invite_code,
    list_invite_codes,
    get_invite_code_by_code,
    delete_invite_code,
    redeem_invite_code,
)
from ._banners import (  # noqa: F401
    create_hosting_banner,
    get_hosting_banner,
    list_hosting_banners,
    get_hosting_banner_audience_ids,
    update_hosting_banner,
    delete_hosting_banner,
    get_active_hosting_banners,
)
from ._feature_requests import (  # noqa: F401
    FEATURE_ENTITLEMENT_COLUMNS,
    FEATURE_LABELS,
    create_instance_feature_request,
    get_instance_feature_request,
    list_instance_feature_requests,
    list_pending_instance_feature_requests,
    cancel_instance_feature_request,
    review_instance_feature_request,
    set_instance_feature_entitlement,
)

# Personal access tokens for the REST API
from ._api_tokens import (  # noqa: F401
    API_SCOPES,
    ADMIN_API_SCOPES,
    API_TOKEN_NAME_MAX_LENGTH,
    MAX_ACTIVE_API_TOKENS,
    api_scopes_for_account,
    parse_api_token_scopes,
    create_api_token,
    get_active_api_token,
    touch_api_token,
    list_api_tokens,
    revoke_api_token,
    record_api_instance_action,
)

# Restoration
from ._restore import restore_hosting_from_backup_zips  # noqa: F401

# Account merging
from ._account_merges import (  # noqa: F401
    create_merge_request,
    get_merge_request,
    get_active_requests_for_account,
    approve_by_source,
    approve_by_target,
    approve_by_admin,
    deny_merge,
    cancel_merge,
    execute_merge,
    admin_execute_merge,
)

# Instance collaborators and ownership transfers
from ._collaborators import (  # noqa: F401
    COLLABORATOR_PERMISSIONS,
    ALL_PERMISSIONS,
    add_collaborator,
    remove_collaborator,
    update_collaborator,
    get_collaborator,
    get_collaborators_for_instance,
    get_shared_instances_for_account,
    collaborator_has_permission,
    is_collaborator,
    count_collaborators,
    remove_all_collaborators,
    create_ownership_transfer,
    get_pending_transfer,
    get_pending_transfers_for_account,
    accept_ownership_transfer,
    cancel_ownership_transfer,
    decline_ownership_transfer,
)
