"""The Caddy configuration for a managed server, and the shipped examples.

One renderer produces both the file ``banana proxy`` installs and the
``deploy/Caddyfile.*`` examples (with ``{$VARIABLE}`` placeholders), so the two
can no longer drift apart. The tests compare the shipped examples with
:func:`example`.

Hardening compared with 1.4: HSTS on every site, request timeouts,
``X-Forwarded-Prefix`` stripped before it reaches the application, and the
portal's ``/internal/*`` endpoints (the on-demand TLS ``ask`` hook) answered
404 from the public listeners; Caddy calls ``ask`` on loopback directly.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from . import MANAGED_MARKER
from .runtime_agent import routes_dir

EXAMPLE_HEADER = (
    "# BananaWiki {mode} example for Caddy 2. Generated by bananawiki.ops.caddy.example({mode!r});\n"
    "# managed servers get the same file from `bananawiki proxy`. Set the {{$VARIABLES}} in Caddy's environment."
)
_HSTS = '\theader Strict-Transport-Security "max-age=31536000"\n'


def _global(email: str, ask: str | None) -> str:
    lines = ["{\n"]
    if email:
        lines.append(f"\temail {email}\n")
    lines.append("\tservers {\n\t\ttimeouts {\n\t\t\tread_header 10s\n\t\t\tread_body 5m\n\t\t\tidle 2m\n\t\t}\n\t}\n")
    if ask:
        lines.append(f"\ton_demand_tls {{\n\t\task {ask}\n\t}}\n")
    lines.append("}\n")
    return "".join(lines)


def _proxy(upstream: str, *, streaming: bool) -> str:
    body = "\t\theader_up -X-Forwarded-Prefix\n"
    if streaming:
        body = "\t\tflush_interval -1\n" + body
    return f"\treverse_proxy {upstream} {{\n{body}\t}}\n"


def render_wiki(domain: str, upstream: str, *, email: str = "", header: str = MANAGED_MARKER) -> str:
    return (
        f"{header}\n" + _global(email, None) + "\n"
        f"{domain} {{\n" + _HSTS + _proxy(upstream, streaming=True) + "}\n"
    )


def render_hosting(domain: str, portal_domain: str, upstream: str, site_root: str, *, email: str = "",
                   header: str = MANAGED_MARKER, routes: str = "/var/lib/bananawiki-routes") -> str:
    """The portal, the static site and, from *routes*, one site block per running wiki.

    The runtime agent writes the wiki site blocks (hostnames to container
    addresses), so wiki traffic goes straight to each tenant; hosts without a
    block fall through to the ``:443`` catch-all (the portal's "not
    available" page) and get certificates only when the portal allows them.
    """
    ask = f"http://{upstream}/internal/domains/authorize"
    common = "(bananawiki_public) {\n" + _HSTS + "\t@internal path /internal/*\n\trespond @internal 404\n}\n"
    return (
        f"{header}\n" + _global(email, ask) + "\n" + common + "\n"
        f"{domain} {{\n\timport bananawiki_public\n\troot * {site_root}\n"
        "\tfile_server {\n\t\thide .git .env\n\t}\n}\n\n"
        f"{portal_domain} {{\n\timport bananawiki_public\n" + _proxy(upstream, streaming=False) + "}\n\n"
        f"import {routes}/*.caddy\n\n"
        ":443 {\n\ttls {\n\t\ton_demand\n\t}\n\timport bananawiki_public\n"
        + _proxy(upstream, streaming=False) + "}\n"
    )


def render(settings: dict[str, Any], *, email: str = "", routes: str | None = None) -> str:
    """The Caddyfile for an installed deployment (*routes*: the agent's routes directory)."""
    domain = settings.get("domain")
    if not domain:
        raise ValueError("Configure a domain before generating an HTTPS proxy configuration.")
    upstream = f"127.0.0.1:{int(settings['port'])}"
    if settings["mode"] == "hosting":
        return render_hosting(domain, settings["portal_domain"], upstream,
                              str(Path(settings["root"]) / "site"), email=email,
                              routes=routes or routes_dir(settings["service"]))
    return render_wiki(domain, upstream, email=email)


def example(mode: str) -> str:
    """The shipped ``deploy/Caddyfile.<mode>`` example (``wiki``, ``hosting`` or ``compose``)."""
    header = EXAMPLE_HEADER.format(mode=mode)
    if mode == "compose":
        return render_wiki("{$WIKI_DOMAIN}", "wiki:5001", email="{$ACME_EMAIL}", header=header)
    if mode == "hosting":
        return render_hosting("{$BASE_DOMAIN}", "{$PORTAL_DOMAIN}", "127.0.0.1:{$HOSTING_PORT:5099}",
                              "{$STATIC_SITE_DIR:/opt/bananawiki/site}", email="{$ACME_EMAIL}", header=header,
                              routes="{$HOSTING_ROUTES_DIR:/var/lib/bananawiki-routes}")
    return render_wiki("{$WIKI_DOMAIN}", "127.0.0.1:{$BW_PORT:5001}", email="{$ACME_EMAIL}", header=header)
