"""The Caddy configuration for a managed server, and the shipped examples.

One renderer produces both the file ``banana proxy`` installs and the
``deploy/Caddyfile.*`` examples (with ``{$VARIABLE}`` placeholders), so the two
can no longer drift apart. The tests compare the shipped examples with
:func:`example`.

Hardening compared with 1.4: HSTS on every site, request timeouts,
``X-Forwarded-Prefix`` stripped before it reaches the application, and the
portal's ``/internal/*`` endpoints (the on-demand TLS ``ask`` hook) answered
404 from the public listeners; Caddy calls ``ask`` on loopback directly.

Behind Cloudflare's proxy (orange-cloud DNS records) the configuration works
in every SSL/TLS mode without redirect loops, and passes the visitor's real
address to the application (see :mod:`bananawiki.ops.caddy_blocks`). Three
certificate modes (:class:`ProxyOptions`, ``bananawiki proxy --tls``):

* ``acme`` (default): Let's Encrypt, per host, on demand for wikis. With
  ``--cloudflare`` the TLS-ALPN-01 challenge, which can never pass through
  Cloudflare's proxy, is disabled so it does not burn the CA's failed
  validation allowance; HTTP-01 must reach port 80 (no forced HTTPS for
  ``/.well-known/acme-challenge/`` at Cloudflare).
* ``cloudflare-dns``: one wildcard certificate ``*.<domain>`` (plus the base
  domain) through the DNS-01 challenge with a Cloudflare API token; needs a
  Caddy build with the ``dns.providers.cloudflare`` module. Every platform
  host is covered at once, nothing depends on port 80 or Cloudflare rules.
* ``origin-cert``: a Cloudflare Origin CA certificate for ``*.<domain>`` and
  ``<domain>`` (Cloudflare SSL/TLS mode "Full (strict)"; browsers do not trust
  it, so every platform record must stay proxied).

Custom domains of hosted wikis always use on-demand ACME certificates.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from . import MANAGED_MARKER
from .caddy_blocks import HSTS, addresses, https_policy, proxy, servers_options, supports_client_ip
from .runtime_agent import routes_dir

EXAMPLE_HEADER = (
    "# BananaWiki {mode} example for Caddy 2. Generated by bananawiki.ops.caddy.example({mode!r});\n"
    "# managed servers get the same file from `bananawiki proxy`. Set the {{$VARIABLES}} in Caddy's environment."
)
TLS_MODES = ("acme", "cloudflare-dns", "origin-cert")
CLOUDFLARE_TOKEN_VARIABLE = "CLOUDFLARE_API_TOKEN"
CLOUDFLARE_DNS_MODULE = "dns.providers.cloudflare"
# Two-label public suffixes (``example.co.uk``) for the Universal SSL depth check.
_SECOND_LEVEL = frozenset({"co", "com", "net", "org", "gov", "edu", "ac", "ne", "or", "go", "gv", "ltd", "plc",
                           "sch", "nhs", "mil", "nom", "gob", "info", "biz", "gen", "firm", "ind"})


@dataclass(frozen=True)
class ProxyOptions:
    """How certificates are obtained, kept in ``config/proxy.json`` (``"tls"``)."""

    tls: str = "acme"
    cloudflare: bool = False
    origin_cert: str = ""
    origin_key: str = ""
    # Caddy 2.7+ (``client_ip_headers``, ``{client_ip}``); older Caddy keeps the 1.6.0 behaviour.
    client_ip: bool = True

    def __post_init__(self) -> None:
        if self.tls not in TLS_MODES:
            raise ValueError(f"The TLS mode must be one of: {', '.join(TLS_MODES)}.")
        if self.tls == "origin-cert" and not (self.origin_cert and self.origin_key):
            raise ValueError("The origin-cert mode needs the certificate and key files.")
        for path in (self.origin_cert, self.origin_key):
            if path and (not path.startswith("/") or any(c in path for c in " \t\r\n{}\"`")):
                raise ValueError("Certificate paths must be absolute and contain no spaces or braces.")

    @property
    def behind_cloudflare(self) -> bool:
        return self.cloudflare or self.tls != "acme"

    @classmethod
    def from_record(cls, record: dict[str, Any] | None, *, client_ip: bool = True) -> ProxyOptions:
        data = (record or {}).get("tls") or {}
        if not isinstance(data, dict):
            data = {}
        return cls(tls=str(data.get("mode") or "acme"), cloudflare=bool(data.get("cloudflare")),
                   origin_cert=str(data.get("origin_cert") or ""), origin_key=str(data.get("origin_key") or ""),
                   client_ip=client_ip)

    def record(self) -> dict[str, Any]:
        value: dict[str, Any] = {"mode": self.tls, "cloudflare": self.cloudflare}
        if self.tls == "origin-cert":
            value.update(origin_cert=self.origin_cert, origin_key=self.origin_key)
        return value


DEFAULT_OPTIONS = ProxyOptions()


def options_for(record: dict[str, Any] | None, version: tuple[int, ...] | None) -> ProxyOptions:
    """The certificate mode saved in ``config/proxy.json``, for the installed Caddy *version*."""
    return ProxyOptions.from_record(record, client_ip=supports_client_ip(version))


def _global(email: str, ask: str | None, options: ProxyOptions) -> str:
    lines = ["{\n"]
    if email:
        lines.append(f"\temail {email}\n")
    if options.behind_cloudflare:
        lines.append("\tcert_issuer acme {\n\t\tdisable_tlsalpn_challenge\n\t}\n")
    lines.append(servers_options(client_ip=options.client_ip))
    if ask:
        lines.append(f"\ton_demand_tls {{\n\t\task {ask}\n\t}}\n")
    lines.append("}\n")
    return "".join(lines)


def _tls(options: ProxyOptions) -> str:
    """The ``tls`` directive of a site the operator's certificate mode covers ('' for ACME)."""
    if options.tls == "cloudflare-dns":
        return f"\ttls {{\n\t\tdns cloudflare {{env.{CLOUDFLARE_TOKEN_VARIABLE}}}\n\t}}\n"
    if options.tls == "origin-cert":
        return f"\ttls {options.origin_cert} {options.origin_key}\n"
    return ""


def _site(hosts: list[str], body: str, tls: str = "") -> str:
    """One site on HTTPS and plain HTTP.

    A manually loaded certificate (``tls <cert> <key>``) configures TLS
    connection policies, which Caddy refuses on the plain HTTP listener, so
    such a site is written as two blocks with the same body.
    """
    if tls.startswith("\ttls /"):
        return (f"{', '.join(hosts)} {{\n{tls}{body}}}\n\n"
                f"{', '.join('http://' + host for host in hosts)} {{\n{body}}}\n\n")
    return f"{addresses(hosts)} {{\n{tls}{body}}}\n\n"


def render_wiki(domain: str, upstream: str, *, email: str = "", header: str = MANAGED_MARKER,
                options: ProxyOptions = DEFAULT_OPTIONS) -> str:
    body = https_policy() + HSTS + proxy(upstream, streaming=True, client_ip=options.client_ip)
    return f"{header}\n" + _global(email, None, options) + "\n" + _site([domain], body, _tls(options)).rstrip("\n") + "\n"


def render_hosting(domain: str, portal_domain: str, upstream: str, site_root: str, *, email: str = "",
                   header: str = MANAGED_MARKER, routes: str = "/var/lib/bananawiki-routes",
                   options: ProxyOptions = DEFAULT_OPTIONS) -> str:
    """The portal, the static site and, from *routes*, one site block per running wiki.

    The runtime agent writes the wiki site blocks (hostnames to container
    addresses), so wiki traffic goes straight to each tenant; hosts without a
    block fall through to the catch-all (the portal's "not available" page)
    and get certificates only when the portal allows them. With a wildcard
    certificate (``cloudflare-dns``, ``origin-cert``) a ``*.<domain>`` block
    catches the platform's own hosts instead, so they never wait for a
    certificate; ``www.<domain>`` redirects to the base domain.
    """
    ask = f"http://{upstream}/internal/domains/authorize"
    client_ip = options.client_ip
    wildcard = options.tls != "acme"
    platform_tls = _tls(options)
    # A manual certificate is named in every site it covers; a managed wildcard is used automatically.
    manual = options.tls == "origin-cert"
    common = (
        "(bananawiki_public) {\n" + HSTS + "\t@internal path /internal/*\n\trespond @internal 404\n}\n\n"
        "(bananawiki_https) {\n" + https_policy() + "}\n"
    )
    app = "\timport bananawiki_https\n\timport bananawiki_public\n" + proxy(upstream, streaming=False,
                                                                           client_ip=client_ip)
    parts = [
        f"{header}\n" + _global(email, ask, options) + "\n" + common + "\n",
        _site([domain], "\timport bananawiki_https\n\timport bananawiki_public\n"
              f"\troot * {site_root}\n\tfile_server {{\n\t\thide .git .env\n\t}}\n", platform_tls),
    ]
    www = "www." + domain
    if portal_domain != www:
        www_tls = platform_tls if manual else ("" if wildcard else "\ttls {\n\t\ton_demand\n\t}\n")
        parts.append(_site([www], f"\tredir https://{domain}{{uri}} 308\n", www_tls))
    under_domain = portal_domain.endswith("." + domain)
    parts.append(_site([portal_domain], app, platform_tls if manual and under_domain else ""))
    if wildcard:
        parts.append(_site(["*." + domain], app, platform_tls))
    parts.append(f"import {routes}/*.caddy\n\n:443, :80 {{\n\ttls {{\n\t\ton_demand\n\t}}\n" + app + "}\n")
    return "".join(parts)


def render(settings: dict[str, Any], *, email: str = "", routes: str | None = None,
           options: ProxyOptions = DEFAULT_OPTIONS) -> str:
    """The Caddyfile for an installed deployment (*routes*: the agent's routes directory)."""
    domain = settings.get("domain")
    if not domain:
        raise ValueError("Configure a domain before generating an HTTPS proxy configuration.")
    upstream = f"127.0.0.1:{int(settings['port'])}"
    if settings["mode"] == "hosting":
        return render_hosting(domain, settings["portal_domain"], upstream,
                              str(Path(settings["root"]) / "site"), email=email,
                              routes=routes or routes_dir(settings["service"]), options=options)
    return render_wiki(domain, upstream, email=email, options=options)


def example(mode: str) -> str:
    """The shipped ``deploy/Caddyfile.<mode>`` example (``wiki``, ``hosting`` or ``compose``)."""
    header = EXAMPLE_HEADER.format(mode=mode)
    if mode == "compose":
        return render_wiki("{$WIKI_DOMAIN}", "wiki:5001", email="{$ACME_EMAIL}", header=header)
    if mode == "hosting":
        return render_hosting("{$BASE_DOMAIN}", "{$PORTAL_DOMAIN}", "127.0.0.1:{$HOSTING_PORT:5099}",
                              "{$STATIC_SITE_DIR:/opt/bananawiki/site}", email="{$ACME_EMAIL}", header=header,
                              routes="{$HOSTING_ROUTES_DIR:/var/lib/bananawiki-routes}")
    return render_wiki("{$WIKI_DOMAIN}", "127.0.0.1:{$BW_PORT:5001}", email="{$ACME_EMAIL}", header=header)


# ── Cloudflare Universal SSL depth ────────────────────────────────────────────


def zone_of(host: str) -> str:
    """The registrable domain of *host* (heuristic: ``example.com``, ``example.co.uk``)."""
    labels = host.lower().rstrip(".").split(".")
    size = 3 if len(labels) >= 3 and labels[-2] in _SECOND_LEVEL and len(labels[-1]) == 2 else 2
    return ".".join(labels[-size:])


def depth(host: str) -> int:
    """Labels between *host* and its zone (``portal.example.com``: 1)."""
    return len(host.rstrip(".").split(".")) - len(zone_of(host).split("."))


def layout_warnings(settings: dict[str, Any], suffix: str = "hosting") -> list[str]:
    """Host names that Cloudflare's free edge certificate (``<zone>``, ``*.<zone>``) does not cover.

    A proxied DNS record for such a name fails in the browser before it
    reaches this server (ERR_SSL_VERSION_OR_CIPHER_MISMATCH).
    """
    domain = (settings.get("domain") or "").lower()
    if not domain:
        return []
    if settings.get("mode") == "hosting":
        wiki = f"<name>-{suffix}.{domain}" if suffix else f"<name>.{domain}"
        hosts = [settings.get("portal_domain") or "", wiki]
    else:
        hosts = [domain]
    portal = domain if depth(domain) == 1 else "portal." + zone_of(domain)
    warnings = []
    for host in hosts:
        probe = host.replace("<name>", "x")
        if host and depth(probe) > 1:
            zone = zone_of(probe)
            warnings.append(
                f"{host} is more than one level below {zone}. Cloudflare's free Universal SSL certificate covers "
                f"only {zone} and *.{zone}, so with a proxied (orange-cloud) DNS record browsers fail with "
                "ERR_SSL_VERSION_OR_CIPHER_MISMATCH. Keep that record DNS-only (grey cloud), add an Advanced "
                "Certificate Manager certificate for it, or use host names one level below the zone"
                + (f" (for example --domain {zone} --portal-domain {portal}; the static site then answers on "
                   f"{zone})." if settings.get("mode") == "hosting" else ".")
            )
    return warnings
